### PR TITLE
Added Outlaw inventory slot

### PR DESCRIPTION
**Pull request by ajilidali**
I sadly didn't get to see if it worked with skins, i played for 4 hours straight and asked all lobbies who had an outlaw skin and nobody did.
I basically implemented it the same way the other weapons were so I'm assuming that skins are just gonna work.

### CODE REVIEW

**Comment by pwall2222** [comment]
The commits are a bit messed up, I will try to fix them for you!
And don't worry I can test the outlaw skin my self, I have a friend that has it.

**Comment by pwall2222** [comment]
The code works flawlessly, maybe we have to arrange the UI better, but the code works perfectly!
image

**Comment by pwall2222** [comment]
I'm gonna squash this and merge it! (I fixed the commit issues)

**Comment by ajilidali** [comment]
I made a drawn proposal for the a new layout in #3.
I tried just moving the rectangles in the VS preview for inventory but what happened is that weapons started overlapping and almost none of those respected their preview.
So what I ended up doing was manually adjusting the margins while running and checking every time the spaces, the final result is flawless imo, but the VS preview is screwed.

**Pull request merged**
